export const SET_ORIGINAL_CHANNELS = "LIST/SET_ORIGINAL_CHANNELS";
export const SET_CHANNELS = "LIST/SET_CHANNELS";
export const SET_FILTER_VALUE = "LIST/SET_FILTER_VALUE";
export const SET_SORTED_CHANNELS = "LIST/SET_SORTED_CHANNELS";
export const CLEAR_SORT_AND_FILTER = "LIST/CLEAR_SORT_AND_FILTER";
export const SET_SORT_VALUE = "LIST/SET_SORT_VALUE";
